# Basic Information 
title: Mahmudul Hoque
position: Former Graduate Teaching
affiliation: Morgan State University
affiliation_link: https://www.morgan.edu/
# affiliation_logo: ./assets/img/Morgan_State_University_Logo.svg.png
email: mahoq1@morgan.edu

# Search Engine Optimization (SEO)
keywords: Mahmudul Hoque, Hoque Mahmudul, Mahmudul, Mahmud, mahoq, Hoque
canonical: https://yaoyaoliu.web.illinois.edu
description: Yaoyao Liu is an assistant professor at the University of Illinois Urbana-Champaign. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=VLEeZg8AAAAJ&hl=en
# github_link: https://github.com/mahmudulhoque/
linkedin: https://www.linkedin.com/in/mahmudul-hoque-40504595/

# Images 
avatar: ./assets/img/Mahmud_Profic.jpg

# Footnotes
footnote: This Wesbite is made from.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
